### ISSUE TITLE
Latest release 2.5.2 has migrations errors

### ISSUE THREAD

**Issue by FinalAngel** [divio/djangocms-text-ckeditor#248]
on django 1.7:

```
  Applying reversion.0002_auto_20141216_1509...Traceback (most recent call last):
  File "src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/finalangel/Sites/django-cms-demo/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/finalangel/Sites/django-cms-demo/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/finalangel/Sites/django-cms-demo/env/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/finalangel/Sites/django-cms-demo/env/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/finalangel/Sites/django-cms-demo/env/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/Users/finalangel/Sites/django-cms-demo/env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/Users/finalangel/Sites/django-cms-demo/env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 96, in apply_migration
    if self.detect_soft_applied(migration):
  File "/Users/finalangel/Sites/django-cms-demo/env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 140, in detect_soft_applied
    apps = project_state.render()
  File "/Users/finalangel/Sites/django-cms-demo/env/lib/python2.7/site-packages/django/db/migrations/state.py", line 75, in render
    "for more" % new_unrendered_models
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'djangocms_text_ckeditor.Text'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more
make: *** [update] Error 1
```

**Comment by FinalAngel** [comment]
``MIGRATION_MODULES`` is not required anymore, just removing the settings resolves that issue

**Comment by blueyed** [comment]
For reference, I've filed a ticket in Django about hiding of the `ImportError` in this case: https://code.djangoproject.com/ticket/25109
