### ISSUE TITLE
Fails to add Text plugin to page

### ISSUE THREAD

**Issue by yunmanger1** [divio/djangocms-text-ckeditor#318]
Getting this error when trying to add Text plugin to page. Using the latest stable djangocms-text-ckeditor==2.9.3 and django-cms from develop. Other plugins are added.

```
ERROR 2016-05-13 12:11:31,104 base 786 140315161945920 Internal Server Error: /en/admin/cms/page/add-plugin/
Traceback (most recent call last):
  File "/app/.envs/tenet/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.envs/tenet/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/app/.envs/tenet/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/.envs/tenet/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/app/.envs/tenet/lib/python2.7/site-packages/django/views/decorators/clickjacking.py", line 41, in wrapped_view
    resp = view_func(*args, **kwargs)
  File "/app/.envs/tenet/lib/python2.7/site-packages/cms/admin/placeholderadmin.py", line 261, in add_plugin
    response = plugin_admin.add_view(request)
  File "/app/.envs/tenet/lib/python2.7/site-packages/djangocms_text_ckeditor/cms_plugins.py", line 64, in add_view
    request, form_url, extra_context
  File "/app/.envs/tenet/lib/python2.7/site-packages/cms/plugin_base.py", line 324, in add_view
    request, form_url, extra_context)
  File "/app/.envs/tenet/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1518, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/app/.envs/tenet/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/.envs/tenet/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/app/.envs/tenet/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/.envs/tenet/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/app/.envs/tenet/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1458, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "/app/.envs/tenet/lib/python2.7/site-packages/djangocms_text_ckeditor/cms_plugins.py", line 85, in get_form
    self.placeholder.slot,
AttributeError: 'NoneType' object has no attribute 'slot'
```

**Comment by vxsx** [comment]
Latest `develop` on django-cms will work only with `feature/sane-add-plugin` on djangocms-text-ckeditor
https://github.com/divio/django-cms/blob/develop/test_requirements/django-1.8.txt#L3

**Comment by czpython** [comment]
Please make sure to use djangocms-text-ckeditor>=3.0.0 with django-cms >= 3.3.0
