### ISSUE TITLE
ckeditor altering source of text element fails to update published view

### ISSUE THREAD

**Issue by td4u78** [divio/djangocms-text-ckeditor#319]
Altering the source of a text element in the frontend fails to update the published source code, although changes are reflected in the edit view's source code.

Following the tutorial from https://www.youtube.com/watch?v=NbsRVfLCE1U, we were instructed to copy and paste some text from his live preview. The text copied contained a div tag which surrounded the entire text, which was also copied. After struggling to figure out why my page did not resemble the tutorial, I found the extra div tags when I viewed the source, and manually removed them. The edit preview properly reflected the change, but the published view did not, still rendering the extra divs. I reset the local server, refreshed the page, even closed the browser and server, with no result.

When trying to again alter the source, altering nothing, just saving the text that correctly shows no div tags, I received the following errors in my command window:
```
[18/May/2016 16:29:57] "GET /en/?edit HTTP/1.1" 200 524977
[18/May/2016 16:29:58] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[18/May/2016 16:29:58] "GET /static/css/modern-business.css HTTP/1.1" 304 0
[18/May/2016 16:29:58] "GET /static/font-awesome/css/font-awesome.min.css HTTP/1.1" 304 0
[18/May/2016 16:29:58] "GET /static/cms/css/cms.base.css?3.2.5 HTTP/1.1" 304 0
[18/May/2016 16:29:58] "GET /static/js/jquery.js HTTP/1.1" 304 0
[18/May/2016 16:29:58] "GET /static/aldryn_bootstrap3/css/base.css HTTP/1.1" 304 0
[18/May/2016 16:29:58] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[18/May/2016 16:29:58] "GET /static/cms/js/modules/jquery.noconflict.pre.js?3.2.5 HTTP/1.1" 304 0
[18/May/2016 16:29:58] "GET /static/cms/js/dist/bundle.toolbar.min.js?3.2.5 HTTP/1.1" 304 0
[18/May/2016 16:29:58] "GET /static/cms/js/modules/jquery.noconflict.post.js?3.2.5 HTTP/1.1" 304 0
[18/May/2016 16:29:58] "GET /static/aldryn_bootstrap3/js/dropzone.min.js HTTP/1.1" 304 0
[18/May/2016 16:29:58] "GET /static/aldryn_bootstrap3/js/dropzone.init.js HTTP/1.1" 304 0
[18/May/2016 16:29:58] "GET /media/filer_public_thumbnails/filer_public/43/65/436597fb-32ff-4bb2-8543-db85fab84748/700x4
50.png__1170x0_q85_subsampling-2_upscale.png HTTP/1.1" 304 0
[18/May/2016 16:29:59] "GET /en/?edit HTTP/1.1" 200 524977
Traceback (most recent call last):
  File "c:\python27\Lib\wsgiref\handlers.py", line 86, in run
    self.finish_response()
  File "c:\python27\Lib\wsgiref\handlers.py", line 128, in finish_response
    self.write(data)
  File "c:\python27\Lib\wsgiref\handlers.py", line 212, in write
    self.send_headers()
  File "c:\python27\Lib\wsgiref\handlers.py", line 270, in send_headers
    self.send_preamble()
  File "c:\python27\Lib\wsgiref\handlers.py", line 194, in send_preamble
    'Date: %s\r\n' % format_date_time(time.time())
  File "c:\python27\Lib\socket.py", line 328, in write
    self.flush()
  File "c:\python27\Lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine
[18/May/2016 16:29:59] "GET /en/?edit HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 4328)
Traceback (most recent call last):
  File "c:\python27\Lib\SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\python27\Lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\DOCUME~1\User\Desktop\DJANGO~1\DJANGO~1\lib\site-packages\django\core\servers\basehttp.py", line 102, in __
init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "c:\python27\Lib\SocketServer.py", line 657, in __init__
    self.finish()
  File "c:\python27\Lib\SocketServer.py", line 716, in finish
    self.wfile.close()
  File "c:\python27\Lib\socket.py", line 283, in close
    self.flush()
  File "c:\python27\Lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine
----------------------------------------
```

I then immediately CTRL+C to exit the server, and received:
```
Unhandled exception in thread started by <function wrapper at 0x020F9FB0>
Traceback (most recent call last):
  File "C:\DOCUME~1\User\Desktop\DJANGO~1\DJANGO~1\lib\site-packages\django\utils\autoreload.py", line 231, in wrapper
```

Running Django 1.8.3, Django CMS 3.2.5, python 2.7.11 running on Windows XP

**Comment by sparkholiday** [comment]
I'm not 100% that this will work, but @stefanfoulis suggested that a security update could be the reason that my djangocms-text-ckeditor was acting weird -- it would create text perfectly upon hitting save in a freshly written text instance, but then would only export raw HTML code if I went back and edited it. If I redeployed the server, the text looked fine again, but having to redeploy the site each time a text field was changed was going to be problematic...

I got extremely lucky, though, after he mentioned the security update being the potential culprit, and went into my Manage Addons page in my project's dashboard, clicked 'configure' on Aldryn django CMS, and clicked the "Leave "render_model" tags unescaped? (security risk)" radio box. It worked fine after that.

See (a probably unneeded) photo [here](http://i.imgur.com/aL4KrTJ.png).

I see that a new update to Aldryn django CMS was just released (like, while I was writing this), maybe it fixes the issue? I'd suggest updating first, and if that doesn't help, click the box (if you don't already have it clicked).

**Comment by FinalAngel** [comment]
@td4u78 and @sparkholiday we addressed these issues in django CMS 3.3 and the latest CKEditor Release 3.0

@sparkholiday your specific issue was also related to external package fixes from treebeard and django-parler.

**Comment by sparkholiday** [comment]
Can confirm: Working fine now without leaving render_model tags unescaped! Thank you!

**Comment by FinalAngel** [comment]
awesome, thanks for the feedback @sparkholiday
