### ISSUE TITLE
install issue: ImportError: cannot import name 'sanitizer'

### ISSUE THREAD

**Issue by tehfink** [divio/djangocms-text-ckeditor#338]
Using the latest, when installing with the following:
```
djangocms  --parent-dir . \
--filer \
--i18n yes \
--use-tz yes \
--timezone America/New_York \
--reversion yes \
--permissions yes \
--languages en-us \
--django-version 1.9 \
--cms-version develop \
--starting-page yes \
--no-input \
--apphooks-reload \
--no-user \
--db sqlite://localhost/project.db \
mysite
```
the install quits with the following error:
```
Traceback (most recent call last):
  File "/Users/fink/Documents/work/MyLittlePony/website/MyLittlePony.com/www./source/3.0/mlp_website-virtualenv/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/Users/fink/Documents/work/MyLittlePony/website/MyLittlePony.com/www./source/3.0/mlp_website-virtualenv/lib/python3.4/site-packages/djangocms_installer/main.py", line 41, in execute
    django.setup_database(config_data)
  File "/Users/fink/Documents/work/MyLittlePony/website/MyLittlePony.com/www./source/3.0/mlp_website-virtualenv/lib/python3.4/site-packages/djangocms_installer/django/__init__.py", line 425, in setup_database
    output = subprocess.check_output(command, env=env)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 617, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/Users/fink/Documents/work/MyLittlePony/website/MyLittlePony.com/www./source/3.0/mlp_website-virtualenv/bin/python3.4', '-W', 'ignore', 'manage.py', 'migrate']' returned non-zero exit status 1
```

According to here:
https://github.com/html5lib/html5lib-python/tree/master/html5lib/filters
sanitizer.py is located in the filters module, so perhaps line 8 from here:
https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/html.py#L8
and line 2 from here:
https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/sanitizer.py#L2
should instead read:
```
from html5lib.filters import sanitizer
from html5lib import treebuilders, treewalkers
```
See release notes here:
https://github.com/html5lib/html5lib-python/blob/14d4851ef707603e8c7a29278572449e4e6f9c22/CHANGES.rst#09999999910b9

**Comment by czpython** [comment]
@tehfink 
We've pinned the html5lib version to be less than `0.99999999`.
Please make sure your environment does not have this version installed.
